#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

workflow:
  rules:
    # There is no need to import this file in a child pipeline (same project or multi project)!!!
    # - We always want to run the child pipeline.
    #     Filter is done in the parent trigger job & for each jon inside the child pipeline
    # - ON_X variables are available in the child pipeline because they are inherited from
    #     - Global parent pipeline variables (its workflow:rules)
    #     - Parent trigger job specific variables
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      auto_cancel:
        on_new_commit: none
    - if: $CI_PIPELINE_SOURCE == "web"
      variables:
        ON_WEB: "true"
      auto_cancel:
        on_new_commit: none
    - if: $CI_PIPELINE_SOURCE == "api"
      variables:
        ON_API: "true"
      auto_cancel:
        on_new_commit: none
    - if: $CI_PIPELINE_SOURCE == "schedule"
      variables:
        ON_SCHEDULE: "true"
      auto_cancel:
        on_new_commit: none
    - if: $CI_COMMIT_TAG
      variables:
        ON_TAG: "true"
      auto_cancel:
        on_new_commit: none
    - if: $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"
      variables:
        ON_MR_TRAIN: "true"
        ON_MR: "true"
      auto_cancel:
        on_new_commit: none
    - if: $CI_MERGE_REQUEST_SOURCE_PROJECT_ID != $CI_MERGE_REQUEST_PROJECT_ID
      variables:
        ON_MR_FORK: "true"
        ON_MR: "true"
      auto_cancel:
        on_new_commit: none
    - if: $CI_MERGE_REQUEST_IID
      # Why $CI_MERGE_REQUEST_IID instead of $CI_PIPELINE_SOURCE == "merge_request_event" ?
      # Child pipelines in a MR have CI_PIPELINE_SOURCE = parent_pipeline
      variables:
        ON_MR: "true"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        ON_DEFAULT_BRANCH: "true"
      auto_cancel:
        on_new_commit: none
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        ON_PROTECTED_BRANCH: "true"
      auto_cancel:
        on_new_commit: none
    - when: never

variables:
  # CI Defaults
  GIT_STRATEGY: fetch
  GIT_DEPTH: "1"
  GET_SOURCES_ATTEMPTS: 3
  ARTIFACT_DOWNLOAD_ATTEMPTS: 3
  RESTORE_CACHE_ATTEMPTS: 3
  CLICOLOR_FORCE: 1
  FORCE_COLOR: 1
  # OCUDU Variables
  OCUDU_REGISTRY_SERVER: registry.gitlab.com # $CI_TEMPLATE_REGISTRY_HOST
  OCUDU_PROJECT_PATH: ocudu/ocudu # $CI_PROJECT_PATH
  OCUDU_REGISTRY_URI: ${OCUDU_REGISTRY_SERVER}/${OCUDU_PROJECT_PATH}

default:
  interruptible: true
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure
      - runner_unsupported
      - unmet_prerequisites
      - scheduler_failure
      - data_integrity_failure
